---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault
      version: 0.19.0
  interval: 30s
  targetNamespace: staging
  values:
    injector:
      replicas: 1
    ingress:
      host: staging.vault.192.168.72.104.nip.io

